# Generated by Django 4.2.30 on 2026-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='days_per_week',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='equipment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='workout_duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='fee',
            field=models.PositiveIntegerField(),
        ),
    ]
