# Generated by Django 4.2.30 on 2026-08-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApp', '0003_foodanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_membership_active',
            field=models.BooleanField(default=True),
        ),
    ]
