# Generated by Django 4.2.30 on 2026-09-21 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='memberbadge',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='🏆', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberbadge',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='memberbadge',
            constraint=models.UniqueConstraint(fields=('member', 'badge'), name='unique_member_badge'),
        ),
    ]
