# Generated by Django 4.2.30 on 2026-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamification', '0002_alter_memberbadge_unique_together_alter_badge_icon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='challengeparticipation',
            constraint=models.UniqueConstraint(fields=('member', 'challenge'), name='unique_challenge_participation'),
        ),
    ]
